# Generated by Django 5.2.7 on 2025-11-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0104_auto_renew_payment_method'),
        ('adserver_auth', '0010_data_all_emails_verified'),
    ]

    operations = [
        # `adserver_auth_user_advertisers` is the implicit through table Django
        # created for the original `User.advertisers` ManyToManyField, so it
        # already carries a UNIQUE (user_id, advertiser_id) constraint. Migration
        # 0009 only adopted the table into an explicit through model via
        # SeparateDatabaseAndState, without touching the database. Issuing the
        # constraint again fails on PostgreSQL with DuplicateTable; only the
        # migration state needs to catch up.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='useradvertisermember',
                    unique_together={('user', 'advertiser')},
                ),
            ],
        ),
    ]
